language: node_js
node_js:
- node
addons:
  ssh_known_hosts:
  - 138.68.163.126
env:
  matrix:
  - MY_VAR=EverythingIsAwesome
before_install:
- openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 138.68.163.126\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- sh .bin/ssh-test.sh
