language: node_js
node_js:
- node
addons:
  ssh_known_hosts:
  - 138.68.163.126
env:
  - SERVER_IP_ADDRESS=138.68.163.126
before_install:
- openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- cat ~/.ssh/known_hosts
after_success:
  # Use BASH instead of DASH! see: https://ubuntuforums.org/showthread.php?t=1932504
  - ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
  # - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  # - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  # - echo "git rev-parse --abbrev-ref HEAD => $(git rev-parse --abbrev-ref HEAD)"
  # - sh .bin/commit-hash.sh
  # - sh .bin/branch.sh
  # - sh .bin/issue.sh
  # debugging https://github.com/dwyl/learn-devops/issues/34
  - echo "TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_BRANCH"
  - if [ $TRAVIS_PULL_REQUEST_BRANCH ]; then 
      sh .bin/deploy.sh;
    fi
