language: node_js
node_js:
- node
addons:
  ssh_known_hosts:
  - 138.68.163.126
env:
  matrix:
  - MY_VAR=EverythingIsAwesome
before_install:
- openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 138.68.163.126\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- cat ~/.ssh/known_hosts
after_success:
  # Use BASH instead of DASH! see: https://ubuntuforums.org/showthread.php?t=1932504
  - ls -al /bin/sh
  - sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh
  - ls -al /bin/sh
  # debugging https://github.com/dwyl/learn-devops/issues/34
  - if [ $TRAVIS_PULL_REQUEST_BRANCH ]; then 
      echo "TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_BRANCH";
      sh .bin/deploy.sh;
    fi
