language: node_js
node_js:
- node
env:
  matrix:
  - MY_VAR=EverythingIsAwesome
  global:
    secure: Yr/YfU7fIqgNoD+xKp+6IKPLC6Vwa9636wcQT+eLDF2zsWsmbU3dyLBNAux5h9itwSQcDMhMAQF183QdpF1nAQOKjYayjWye42CiZjxxmt5uo8T393JgJS+SQO3nxBOuf35moWu69ekhlMXeIpSHBJLQA0jcgWB+HeKb5I9shBmcEDikb2QWlpFI7LK53eu/l3aegzcNHWS28sQxN48THH8GkKDBNovVhMxxJvV5d+Ke3jHtGtHLD2sWEuiHWafM3cbV2XeIX0LyERYX5wnkxE9tZWrfY8H9P4UXBGLDJwkSJb18ASUCPGHFaRy1aY5b/WlIDK6l69tLTnA4e5PkmF50ElQFzS442GW2FL+Y8kBIvW6PTB1n+Fq/6d9aVTmA0cKYi6N+pdvEND6w+gtE10F9a6l/9PFbxj8b5/6M49nKyGeR/1fmcpluh3pFy6kPuEn9FM6KBIbqxi9q/h9F42Q+23Yr/gaVOLFsa45WUZtyQlNjNhKPwNyo/tyALvTt6sjhM711AtsH6geTdkKxlp+f/gG0j2NbJLK5ArLMF32WMjs3xF7oBAk4GNTZ1s+QnE7tFzJBPBXwYNL4Mzj5SZ/i1bPcRf3hjuiugwIMM+kVZwMZ8a4EYNQdHuPgOfBj4UvnBQg1XIaGBy/dCpXcuFJEemxEnLz5I3CvlHiHBiE=
before_install:
  - openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv
    -in deploy_key.enc -out ./deploy_key -d
after_success:
  - if [ $SSH_KEY_PASSPHRASE ]; then
      IP="138.68.163.126";
      USER="root";
      SSH="$SSH_KEY_PASSPHRASE | ssh $USER@$IP";
      RELOAD="nginx -t && nginx -s reload &> /dev/null";
      $SSH $RELOAD;
    fi