language: node_js
node_js:
- node
env:
  - SERVER_IP_ADDRESS=138.68.163.126

before_install: # setup the RSA key for use in Dokku Deployment:
- openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
# Use BASH instead of DASH! see: https://ubuntuforums.org/showthread.php?t=1932504
- ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
- sh .bin/commit-hash.sh

after_success:
  # - echo "git rev-parse --verify HEAD => $(git rev-parse --verify HEAD)"
  # - echo "TRAVIS_COMMIT_RANGE => $TRAVIS_COMMIT_RANGE"
  - if [ $TRAVIS_PULL_REQUEST_BRANCH ]; then
      sh .bin/deploy.sh;
    fi
